apiVersion: v1
kind: Service
metadata:
  name: symply-care-frontend-service
  labels:
    app: symply-care-frontend
spec:
  selector:
    app: symply-care-frontend
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 80   
  type: NodePort
