name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag symply_care:$(date +%s)
    - name: Tag the image
      run: docker tag symply_care:$(date +%s) ezratarab/symply_care:latest
    - name: Push the image
      run: docker push ezratarab/symply_care:latest
